// Generated from GameData/Libs/EntityArchetypes/*.xml (SGW3 3.8.6.53) by the trainer build notes; do not edit.
#pragma once
struct SpawnEntry { const char *group; const char *archetype; const char *cls; };
static const SpawnEntry kSpawnCatalog[] = {
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_B", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_C", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_D", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Sniper", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Heavy", "ci_heavy" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Reinforcements.Commando_A", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Reinforcements.Commando_B", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Reinforcements.Commando_C", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Reinforcements.Commando_D", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_E", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Animals.Rottweiler", "ci_rottweiler" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Heavy_B", "ci_heavy" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Heavy_C", "ci_heavy" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Sniper_B", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Sniper_C", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_David", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Mid", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Mid_B", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Mid_C", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_F", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_G", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mercenaries.Regular_A", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mercenaries.Regular_B", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mercenaries.Regular_C", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mercenaries.Mid", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mercenaries.General", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mercenaries.Heavy_A", "ci_heavy" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mercenaries.Heavy_B", "ci_heavy" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mercenaries.Heavy_C", "ci_heavy" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mercenaries.Sniper_A", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Heavy_D", "ci_heavy" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Mid_Demolish", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Mid_Leader", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.DemoTest", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mercenaries.Regular_D", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mercenaries.Mid_Demolish", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mercenaries.Mid_Leader", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Quarry guard.Soldier1", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Quarry guard.Soldier2", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Quarry guard.Soldier3", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_NoVoice", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_B_NoVoice", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_C_NoVoice", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_D_NoVoice", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_E_NoVoice", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_F_NoVoice", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_G_NoVoice", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Lev_Trapsh", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Debug_Demolish", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.DebugDemo", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.RightHand_Davit", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_noWoundedState", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_B_noWoundedState", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_C_noWoundedState", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_D_noWoundedState", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_E_noWoundedState", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_F_noWoundedState", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Sniper_noWoundedState", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Sniper_B_noWoundedState", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Sniper_C_noWoundedState", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.PerfTestPriest", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Mid_noWoundedState", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Mid_C_noWoundedState", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Mid_B_noWoundedState", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Heavy_NoVoice", "ci_heavy" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Heavy_B_NoVoice", "ci_heavy" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Heavy_C_NoVoice", "ci_heavy" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Heavy_D_NoVoice", "ci_heavy" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Boris_Druganin", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Alper_Erdal", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Amin_Nabiyev", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.dr_Darya_Kuznetsov", "ci_female" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Capt_Abel_Dadiani_Bpd", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Capt_Dorofey_Ketsba", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Capt_Ioseb_Pogodin", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Joost_Arends", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Chaarkit", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Era_Baris", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Grivapsh", "ci_female" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Medea_Janashia", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Stepan_Chbaarta", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Tanya_Ratsba", "ci_female" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Vladislav_Bagapsh", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.dr_Darya_Kuznetsov_m", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Grivapsh_m", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Scorned_Sixteen.Tanya_Ratsba_m", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Demolish", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_Empowered", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Sniper_Empowered", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Sniper_Elite", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Heavy_Empowered", "ci_heavy" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Mid_Empowered", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Demolish_Empowered", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Demolish_Elite", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Fabular.Igor_Zaitsev", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_Empowered_B", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_Empowered_C", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Mid_Elite", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Regular_Elite", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Heavy_Elite", "ci_heavy" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mission.Mid_Mission", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mission.Mid_Leader_Mission", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mission.Demolish_Empowered_Mission", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mission.Regular_Empowered_Mission", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Mission.Mid_B_Mission", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Sabotage_Soldiers.Regular_A", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Sabotage_Soldiers.Regular_B", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Sabotage_Soldiers.Regular_C", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Sabotage_Soldiers.Regular_E", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Sabotage_Soldiers.Regular_D", "ci_human" },
    { "Pro-Russian militia (hostile)", "Pro_Russians.Soldiers.Heavy_Elite_NoScoutMode", "ci_heavy" },
    { "Russians (hostile)", "Russians.Soldiers.Regular", "ci_human" },
    { "Russians (hostile)", "Russians.Soldiers.Sniper", "ci_human" },
    { "Russians (hostile)", "Russians.Reinforcements.Commando_A", "ci_human" },
    { "Russians (hostile)", "Russians.Soldiers.Squad Leader", "ci_human" },
    { "Russians (hostile)", "Russians.Soldiers.Heavy", "ci_heavy" },
    { "Russians (hostile)", "Russians.Story.General", "ci_humanBig" },
    { "Russians (hostile)", "Russians.Story.Main_Scientist", "ci_female" },
    { "Russians (hostile)", "Russians.Story.Foreman", "ci_female" },
    { "Russians (hostile)", "Russians.Soldiers.Regular_B", "ci_human" },
    { "Russians (hostile)", "Russians.Soldiers.Regular_C", "ci_human" },
    { "Russians (hostile)", "Russians.Soldiers.Regular_A", "ci_human" },
    { "Russians (hostile)", "Russians.Soldiers.Regular_D", "ci_human" },
    { "Russians (hostile)", "Russians.Soldiers.infantry_worker", "ci_human" },
    { "Russians (hostile)", "Russians.Reinforcements.Commando_B", "ci_human" },
    { "Russians (hostile)", "Russians.Reinforcements.Commando_C", "ci_human" },
    { "Russians (hostile)", "Russians.Reinforcements.Commando_D", "ci_human" },
    { "Russians (hostile)", "Russians.Story.Mayor", "ci_human" },
    { "Russians (hostile)", "Russians.Animals.Rottweiler1", "ci_rottweiler" },
    { "Russians (hostile)", "Russians.Soldiers.Squad Leader_B", "ci_human" },
    { "Russians (hostile)", "Russians.Soldiers.Squad Leader_C", "ci_human" },
    { "Russians (hostile)", "Russians.Story.Captain_dmitry", "ci_human" },
    { "Russians (hostile)", "Russians.Soldiers.Regular_noWoundedState", "ci_human" },
    { "Russians (hostile)", "Russians.Soldiers.Regular_A_noWoundedState", "ci_human" },
    { "Russians (hostile)", "Russians.Soldiers.Regular_B_noWoundedState", "ci_human" },
    { "Russians (hostile)", "Russians.Soldiers.Regular_C_noWoundedState", "ci_human" },
    { "Russians (hostile)", "Russians.Soldiers.Regular_D_noWoundedState", "ci_human" },
    { "Russians (hostile)", "Russians.Soldiers.Sniper_noWoundedState", "ci_human" },
    { "Russians (hostile)", "Russians.Story.Toothless", "ci_humanBig" },
    { "Criminals (hostile)", "Criminals.Soldiers.Regular", "ci_human" },
    { "Criminals (hostile)", "Criminals.Soldiers.Heavy", "ci_heavy" },
    { "Criminals (hostile)", "Criminals.Soldiers.Regular_street", "ci_human" },
    { "Criminals (hostile)", "Criminals.Soldiers.Leader", "ci_human" },
    { "Criminals (hostile)", "Criminals.Main.Nana", "ci_female" },
    { "Criminals (hostile)", "Criminals.Strippers.stripper_A", "ci_female" },
    { "Criminals (hostile)", "Criminals.Strippers.stripper_B", "ci_female" },
    { "Criminals (hostile)", "Criminals.Strippers.stripper_C", "ci_female" },
    { "Criminals (hostile)", "Criminals.Main.Nana_Bodyguard", "ci_human" },
    { "Criminals (hostile)", "Criminals.Casino.Boss", "ci_human" },
    { "Criminals (hostile)", "Criminals.Main.Gambler_1", "ci_human" },
    { "Criminals (hostile)", "Criminals.Casino.Croupier_A", "ci_human" },
    { "Criminals (hostile)", "Criminals.Casino.Croupier_B", "ci_human" },
    { "Criminals (hostile)", "Criminals.Casino.Croupier_C", "ci_human" },
    { "Criminals (hostile)", "Criminals.Casino.Croupier_D", "ci_human" },
    { "Criminals (hostile)", "Criminals.Soldiers.Regular_Shotgun", "ci_human" },
    { "Criminals (hostile)", "Criminals.Soldiers.Regular_B", "ci_human" },
    { "Criminals (hostile)", "Criminals.Soldiers.Regular_C", "ci_human" },
    { "Criminals (hostile)", "Criminals.Soldiers.Heavy_B", "ci_heavy" },
    { "Criminals (hostile)", "Criminals.Soldiers.Heavy_C", "ci_heavy" },
    { "Criminals (hostile)", "Criminals.Soldiers.Regular_D", "ci_human" },
    { "Criminals (hostile)", "Criminals.Soldiers.Regular_E", "ci_human" },
    { "Criminals (hostile)", "Criminals.Separatist.HQ_Guard_Sep_A", "ci_human" },
    { "Criminals (hostile)", "Criminals.Separatist.HQ_Guard_Sep_B", "ci_human" },
    { "Criminals (hostile)", "Criminals.Separatist.HQ_Guard_Sep_C", "ci_human" },
    { "Criminals (hostile)", "Criminals.Separatist.HQ_Guard_Sep_D", "ci_human" },
    { "Criminals (hostile)", "Criminals.Separatist.HQ_Guard_Sep_E", "ci_human" },
    { "Criminals (hostile)", "Criminals.Mission.Kovac", "ci_human" },
    { "Criminals (hostile)", "Criminals.Mission.Xaara", "ci_human" },
    { "Criminals (hostile)", "Criminals.Mission.QuarryLeader", "ci_human" },
    { "Criminals (hostile)", "Criminals.Mission.Winery_Leader", "ci_human" },
    { "Criminals (hostile)", "Criminals.Soldiers.Regular_Support1", "ci_human" },
    { "Criminals (hostile)", "Criminals.Soldiers.Regular_Support2", "ci_human" },
    { "Criminals (hostile)", "Criminals.Soldiers.Regular_Support3", "ci_human" },
    { "23 Society (hostile)", "23_Society.Soldiers.Regular", "ci_maleFast" },
    { "23 Society (hostile)", "23_Society.Soldiers.Shield", "ci_maleFast" },
    { "Americans (neutral)", "Americans.Soldiers.Regular_1", "ci_human" },
    { "Americans (neutral)", "Americans.Soldiers.Regular_2", "ci_human" },
    { "Americans (neutral)", "Americans.Soldiers.Female_Sniper", "ci_female" },
    { "Americans (neutral)", "Americans.Soldiers.Cole_anderson", "ci_human" },
    { "Americans (neutral)", "Americans.Soldiers.Diaz", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Reinforcements.Commando_A", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Reinforcements.Commando_B", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Reinforcements.Commando_C", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Reinforcements.Commando_D", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Animals.Rottweiler", "ci_rottweiler" },
    { "Pro-Americans", "Pro_Americans.Soldiers.General", "ci_heavy" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Heavy", "ci_heavy" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Infantry_B", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Infantry", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Regular", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Sniper", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Squad Leader_NoWoundedState", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Special_Infantry_Coop", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Infantry_C", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Squad Leader", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Mid_normal", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Demolish_normal", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Heavy_normal", "ci_heavy" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Regular_normal", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Sniper_normal", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Demolish_Elite", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Demolish_Empowered", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Heavy_Elite", "ci_heavy" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Heavy_Empowered", "ci_heavy" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Mid_Elite", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Mid_Empowered", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Regular_Elite", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Regular_Empowered", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Sniper_Elite", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Sniper_Empowered", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Mission.Officer_Mid", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Most_Wanted.Target_CH_G", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Most_Wanted.Target_CH_I", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Criminals.Criminal_Leader", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Criminals.Regular", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Criminals.Regular_Shotgun", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Criminals.Regular_B", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Criminals.Regular_C", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Criminals.Regular_D", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Regular_Empowered_Flashlight", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Mid_Empowered_Flashlight", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Mid_normal_Flashlight", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Regular_normal_Flashlight", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Mission.Heavy_Empowered_MH05", "ci_heavy" },
    { "Pro-Americans", "Pro_Americans.Mission.Demolish_Empowered_MH05", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Mission.Mid_Empowered_MH05", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Mission.Regular_Empowered_MH05", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Mission.Sniper_Empowered_MH05", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Mission.Sniper_Elite_MH05", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Mission.Regular_normal_MH05", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.Regular_normal_Gen_Leonidze", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Most_Wanted.Target_CarteBlanche", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.US_Soldier_Demolish", "ci_human" },
    { "Pro-Americans", "Pro_Americans.Soldiers.US_Soldier_Elite", "ci_human" },
    { "Civilians", "Civilians.Male.City_1", "ci_human" },
    { "Civilians", "Civilians.Workers.Worker_1", "ci_human" },
    { "Civilians", "Civilians.Workers.Worker_2", "ci_human" },
    { "Civilians", "Civilians.Workers.Worker_3", "ci_human" },
    { "Civilians", "Civilians.Scientists.Scientist_1", "ci_human" },
    { "Civilians", "Civilians.Scientists.Scientist_2", "ci_human" },
    { "Civilians", "Civilians.Scientists.Scientist_3", "ci_human" },
    { "Civilians", "Civilians.Scientists.Scientist_4", "ci_human" },
    { "Civilians", "Civilians.Workers.Worker_4", "ci_human" },
    { "Civilians", "Civilians.Workers.Miner", "ci_human" },
    { "Civilians", "Civilians.Story.Main_Scientist", "ci_female" },
    { "Civilians", "Civilians.Workers.Worker_5", "ci_human" },
    { "Civilians", "Civilians.Villagers.Female_1", "ci_female" },
    { "Civilians", "Civilians.Villagers.Female_2", "ci_female" },
    { "Civilians", "Civilians.Villagers.Male_1", "ci_human" },
    { "Civilians", "Civilians.Villagers.Male_2", "ci_human" },
    { "Civilians", "Civilians.Villagers.Male_3", "ci_human" },
    { "Civilians", "Civilians.Villagers.Male_4", "ci_maleOld" },
    { "Civilians", "Civilians.Villagers.Female_3", "ci_female" },
    { "Civilians", "Civilians.Villagers.Female_4", "ci_female" },
    { "Civilians", "Civilians.Villagers.Female_5", "ci_femaleOld" },
    { "Civilians", "Civilians.Workers.Worker_Global_Avtivity", "ci_human" },
    { "Civilians", "Civilians.Story.Robert_North", "ci_female" },
    { "Civilians", "Civilians.Workers.Train_Worker", "ci_human" },
    { "Civilians", "Civilians.Airport.Worker_1", "ci_human" },
    { "Civilians", "Civilians.Airport.Worker_2", "ci_human" },
    { "Civilians", "Civilians.Airport.Worker_3", "ci_human" },
    { "Civilians", "Civilians.Airport.Mechanic_1", "ci_human" },
    { "Civilians", "Civilians.Airport.Mechanic_2", "ci_human" },
    { "Civilians", "Civilians.Airport.Pilot_1", "ci_human" },
    { "Civilians", "Civilians.Airport.Pilot_2", "ci_human" },
    { "Civilians", "Civilians.Airport.Stewardess_1", "ci_female" },
    { "Civilians", "Civilians.Airport.Stewardess_2", "ci_female" },
    { "Civilians", "Civilians.Airport.Stewardess_3", "ci_female" },
    { "Civilians", "Civilians.Airport.Researcher", "ci_human" },
    { "Civilians", "Civilians.Airport.Investigator_1", "ci_human" },
    { "Civilians", "Civilians.Citizen.Male_1", "ci_human" },
    { "Civilians", "Civilians.Citizen.Male_2", "ci_human" },
    { "Civilians", "Civilians.Citizen.Male_3", "ci_human" },
    { "Civilians", "Civilians.Citizen.Male_4", "ci_human" },
    { "Civilians", "Civilians.Citizen.Female_1", "ci_female" },
    { "Civilians", "Civilians.Citizen.Female_3", "ci_female" },
    { "Civilians", "Civilians.Citizen.Female_4", "ci_female" },
    { "Civilians", "Civilians.Citizen.Female_5", "ci_female" },
    { "Civilians", "Civilians.Citizen.kid_1", "ci_kid" },
    { "Civilians", "Civilians.Citizen.kid_2", "ci_kid" },
    { "Civilians", "Civilians.Citizen.kid_3", "ci_kid" },
    { "Civilians", "Civilians.Citizen.kid_4", "ci_kid" },
    { "Civilians", "Civilians.Villagers.kid_1", "ci_kid" },
    { "Civilians", "Civilians.Villagers.kid_2", "ci_kid" },
    { "Civilians", "Civilians.Villagers.kid_3", "ci_kid" },
    { "Civilians", "Civilians.Villagers.kid_4", "ci_kid" },
    { "Civilians", "Civilians.Villagers.Cooking_woman", "ci_female" },
    { "Civilians", "Civilians.Villagers.Waiter", "ci_human" },
    { "Civilians", "Civilians.Workers.Train_Conductor", "ci_human" },
    { "Civilians", "Civilians.Hospital.Doctor_1", "ci_human" },
    { "Civilians", "Civilians.Hospital.Doctor_2", "ci_human" },
    { "Civilians", "Civilians.Hospital.Nurse_1", "ci_female" },
    { "Civilians", "Civilians.Hospital.Nurse_2", "ci_female" },
    { "Civilians", "Civilians.Hospital.patient_male", "ci_human" },
    { "Civilians", "Civilians.Hospital.patient_female", "ci_female" },
    { "Civilians", "Civilians.Villagers.Lumberjack_1", "ci_human" },
    { "Civilians", "Civilians.Villagers.Lumberjack_2", "ci_human" },
    { "Civilians", "Civilians.Student.Female_1", "ci_female" },
    { "Civilians", "Civilians.Student.Female_2", "ci_female" },
    { "Civilians", "Civilians.Student.Female_3", "ci_female" },
    { "Civilians", "Civilians.Student.Female_teacher", "ci_female" },
    { "Civilians", "Civilians.Student.Male_1", "ci_human" },
    { "Civilians", "Civilians.Student.Male_2", "ci_human" },
    { "Civilians", "Civilians.Student.Male_3", "ci_human" },
    { "Civilians", "Civilians.Student.Male_teacher_1", "ci_human" },
    { "Civilians", "Civilians.Student.Male_teacher_2", "ci_human" },
    { "Civilians", "Civilians.Citizen.teenager_1", "ci_female" },
    { "Civilians", "Civilians.Citizen.teenager_2", "ci_female" },
    { "Civilians", "Civilians.Citizen.Sportman_1", "ci_human" },
    { "Civilians", "Civilians.Citizen.Sportman_2", "ci_human" },
    { "Civilians", "Civilians.Citizen.Motobiker_1", "ci_human" },
    { "Civilians", "Civilians.Citizen.Motobiker_2", "ci_human" },
    { "Civilians", "Civilians.RedCross.Male_1", "ci_human" },
    { "Civilians", "Civilians.RedCross.Male_2", "ci_human" },
    { "Civilians", "Civilians.Casino.casino_gambler_1", "ci_human" },
    { "Civilians", "Civilians.Casino.casino_gambler_2", "ci_human" },
    { "Civilians", "Civilians.Casino.casino_gambler_3", "ci_human" },
    { "Civilians", "Civilians.Casino.casino_gambler_4", "ci_human" },
    { "Civilians", "Civilians.Workers.Fireman", "ci_human" },
    { "Civilians", "Civilians.Police.policeman_male", "ci_human" },
    { "Civilians", "Civilians.Police.policeman_female", "ci_female" },
    { "Civilians", "Civilians.Police.policeman_riot", "ci_human" },
    { "Civilians", "Civilians.Police.policeman_river_1", "ci_human" },
    { "Civilians", "Civilians.Police.policeman_river_2", "ci_human" },
    { "Civilians", "Civilians.Workers.Foreman", "ci_female" },
    { "Civilians", "Civilians.Citizen.Male_5", "ci_human" },
    { "Civilians", "Civilians.Citizen.Male_6", "ci_human" },
    { "Civilians", "Civilians.Villagers.Butcher_1", "ci_human" },
    { "Civilians", "Civilians.Villagers.Female_6", "ci_femaleOld" },
    { "Civilians", "Civilians.Scientists.Scientist_5", "ci_human" },
    { "Civilians", "Civilians.Separatists.Sep_Restricted_Zone_1", "ci_human" },
    { "Civilians", "Civilians.Separatists.Sep_Restricted_Zone_2", "ci_human" },
    { "Civilians", "Civilians.Separatists.Sep_Restricted_Zone_3", "ci_human" },
    { "Civilians", "Civilians.Separatists.Sep_Restricted_Zone_4", "ci_human" },
    { "Civilians", "Civilians.Separatists.Sep_Restricted_Zone_5", "ci_human" },
    { "Civilians", "Civilians.Criminals.Fighter_1", "ci_human" },
    { "Civilians", "Civilians.Criminals.Fighter_2", "ci_human" },
    { "Civilians", "Civilians.Scientists.Scientist_ProRus_1", "ci_human" },
    { "Civilians", "Civilians.Scientists.Scientist_ProRus_2", "ci_human" },
    { "Civilians", "Civilians.Scientists.Scientist_ProRus_3", "ci_human" },
    { "Civilians", "Civilians.Scientists.Scientist_ProRus_4", "ci_human" },
    { "Civilians", "Civilians.Scientists.Scientist_ProRus_5", "ci_human" },
    { "Civilians", "Civilians.Resistance.Grigol", "ci_human" },
    { "Civilians", "Civilians.Story.Koba", "ci_human" },
    { "Civilians", "Civilians.Story.Grigol", "ci_human" },
    { "Civilians", "Civilians.Mission.Imeda", "ci_human" },
    { "Civilians", "Civilians.Mission.Anri", "ci_human" },
    { "Civilians", "Civilians.Airport.Investigator_2", "ci_human" },
    { "Civilians", "Civilians.Airport.Investigator_3", "ci_human" },
    { "Civilians", "Civilians.Mission.Scientist_Mission", "ci_human" },
    { "Aggressive animals", "Aggressive_Animals.Wolf", "ci_wolf" },
    { "Aggressive animals", "Aggressive_Animals.Prologue_Wolf", "ci_wolf" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.Lea", "ci_human" },
    { "Story characters", "Fabular_Characters.Separatist.Tomas", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.FrankSimms", "ci_heavy" },
    { "Story characters", "Fabular_Characters.Wedding.Groom", "ci_human" },
    { "Story characters", "Fabular_Characters.Wedding.Bride", "ci_female" },
    { "Story characters", "Fabular_Characters.Journalists.Shelby", "ci_female" },
    { "Story characters", "Fabular_Characters.Journalists.Tim", "ci_human" },
    { "Story characters", "Fabular_Characters.Separatist.Inna", "ci_female" },
    { "Story characters", "Fabular_Characters.Russians.General", "ci_heavy" },
    { "Story characters", "Fabular_Characters.Wedding.Priest", "ci_human" },
    { "Story characters", "Fabular_Characters.Russians.Mayor", "ci_human" },
    { "Story characters", "Fabular_Characters.Separatist.Davit", "ci_human" },
    { "Story characters", "Fabular_Characters.Separatist.Simoni", "ci_kid" },
    { "Story characters", "Fabular_Characters.Wedding.Orchestra_1", "ci_human" },
    { "Story characters", "Fabular_Characters.Wedding.Orchestra_2", "ci_human" },
    { "Story characters", "Fabular_Characters.Wedding.Orchestra_3", "ci_human" },
    { "Story characters", "Fabular_Characters.Russians.Chopper_driver", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.RobertNorth", "ci_human" },
    { "Story characters", "Fabular_Characters.Wedding.LeaBridesmaid", "ci_human" },
    { "Story characters", "Fabular_Characters.Cutscenes.LeaNaked", "ci_human" },
    { "Story characters", "Fabular_Characters.Cutscenes.JonNaked", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.SwissBanker", "ci_human" },
    { "Story characters", "Fabular_Characters.SaveLea.Lea", "ci_human" },
    { "Story characters", "Fabular_Characters.SaveLea.Nana", "ci_human" },
    { "Story characters", "Fabular_Characters.SaveLea.Simony", "ci_kid" },
    { "Story characters", "Fabular_Characters.SaveLea.David", "ci_human" },
    { "Story characters", "Fabular_Characters.SaveLea.Nana_guard", "ci_human" },
    { "Story characters", "Fabular_Characters.SaveLea.Separatist", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.Lea_postpregnant", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.Lea_pregnant_7m", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.Lea_pregnant_9m", "ci_human" },
    { "Story characters", "Fabular_Characters.Separatist.Simoni_separatist", "ci_kid" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.RobertNorth_criminal", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.RobertNorth_russian", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.RobertNorth_secret_service", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.RobertNorth_policeman", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.RobertNorth_inmask", "ci_human" },
    { "Story characters", "Fabular_Characters.Wedding.Georgian_Traitor", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.Prisoner_1hp", "ci_human" },
    { "Story characters", "Fabular_Characters.Soldiers.Overwatch_Agent", "ci_human" },
    { "Story characters", "Fabular_Characters.Separatist.BurningUpLeader", "ci_humanBig" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.Raquel", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.Awas", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.ColeAnderson", "ci_human" },
    { "Story characters", "Fabular_Characters.Lydia_DLC.Lydia_Partner", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.Lea_military", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.Lydia_wedding", "ci_human" },
    { "Story characters", "Fabular_Characters.Fabular_Characters.Vasilisk", "ci_human" },
    { "Characters", "Characters.Friendly.Norm_Rifle", "Human" },
    { "Characters", "Characters.Enemy.Norm_Rifle", "Human" },
    { "Characters", "Characters.Enemy.Easy_Rifle", "Human" },
    { "Characters", "Characters.Enemy.Hard_Rifle", "Human" },
    { "Characters", "Characters.Friendly.Easy_Rifle", "Human" },
    { "Characters", "Characters.Friendly.Hard_Rifle", "Human" },
};
