"""Build the Lua side: framework header for the mod loader + mod paks.

Usage:
  python tools/build.py                      release paks
  python tools/build.py --dev                + zzz_sgw3_dev.pak (hot reload / exec; see tools/dev/devhooks.lua)
  python tools/build.py --main-lua <path>    + optional/zzzz_sgw3_framework_fallback.pak, built from the game's own
                                               Scripts/main.lua (decompiled from your install; never committed)

Outputs:
  build/generated/framework_lua.h      framework/src/Framework.lua embedded in sgw3_modloader.asi
  build/paks/zzz_sgw3_bhop.pak         Bunny Hop      -> Scripts/AutoLoad/sgw3_bhop/init.lua
  build/paks/zzz_sgw3_trainer.pak      Trainer+editor -> Scripts/AutoLoad/sgw3_trainer/init.lua
  build/paks/zzz_hello_world.pak       example mod
Mod paks never contain Scripts/main.lua: sgw3_modloader.asi injects the framework.
"""
import argparse
import os
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD = os.path.join(ROOT, "build")


def read(*parts):
    return open(os.path.join(ROOT, *parts), encoding="utf-8").read()


def pak(path, entries):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        for name, text in entries:
            z.writestr(name, text)
    print("built", os.path.relpath(path, ROOT))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dev", action="store_true")
    ap.add_argument("--main-lua", help="the game's decompiled Scripts/main.lua (for the fallback pak)")
    a = ap.parse_args()

    framework = read("framework", "src", "Framework.lua")

    # framework embedded in the ASI; MSVC limits one string literal piece to ~16 KB, so split into adjacent literals
    assert ')SGW3"' not in framework
    chunks = [framework[i:i + 12000] for i in range(0, len(framework), 12000)]
    os.makedirs(os.path.join(BUILD, "generated"), exist_ok=True)
    open(os.path.join(BUILD, "generated", "framework_lua.h"), "w", encoding="utf-8").write(
        "// Generated by tools/build.py from framework/src/Framework.lua - do not edit.\n#pragma once\n"
        "static const char kFrameworkLua[] =\n" + "\n".join('R"SGW3(' + c + ')SGW3"' for c in chunks) + ";\n")
    print("wrote build/generated/framework_lua.h")

    paks = os.path.join(BUILD, "paks")
    pak(os.path.join(paks, "zzz_sgw3_bhop.pak"), [
        ("Scripts/AutoLoad/sgw3_bhop/init.lua", 'Script.ReloadScript("Scripts/Bhop/Bhop.lua")\n'),
        ("Scripts/Bhop/Bhop.lua", read("mods", "bhop", "Scripts", "Bhop", "Bhop.lua")),
    ])
    pak(os.path.join(paks, "zzz_sgw3_trainer.pak"), [
        ("Scripts/AutoLoad/sgw3_trainer/init.lua",
         'Script.ReloadScript("Scripts/Trainer/Trainer.lua")\nScript.ReloadScript("Scripts/Trainer/Editor.lua")\n'),
        ("Scripts/Trainer/Trainer.lua", read("mods", "trainer", "Scripts", "Trainer", "Trainer.lua")),
        ("Scripts/Trainer/Editor.lua", read("mods", "trainer", "Scripts", "Trainer", "Editor.lua")),
    ])
    pak(os.path.join(paks, "zzz_hello_world.pak"), [
        ("Scripts/AutoLoad/hello_world/init.lua",
         read("framework", "examples", "hello_world", "Scripts", "AutoLoad", "hello_world", "init.lua")),
    ])
    if a.dev:
        pak(os.path.join(paks, "zzz_sgw3_dev.pak"), [("Scripts/AutoLoad/00_sgw3_dev/init.lua", read("tools", "dev", "devhooks.lua"))])
    if a.main_lua:
        main_lua = open(a.main_lua, encoding="utf-8").read()
        pak(os.path.join(paks, "optional", "zzzz_sgw3_framework_fallback.pak"), [
            ("Scripts/main.lua", main_lua + '\n-- SGW3 Mod Framework (fallback start for setups without sgw3_modloader.asi)\n'
                                           'Script.ReloadScript("Scripts/SGW3/Framework.lua")\n'),
            ("Scripts/SGW3/Framework.lua", framework),
        ])


if __name__ == "__main__":
    main()
