"""Regenerate the trainer's model list and NPC spawn catalog from a local SGW3 install.

Usage: python tools/gen_catalogs.py "<game folder>"

Writes mods/trainer/native/sgw3_models.txt (every .cgf/.cga in GameSDK/Objects*.pak, LODs excluded) and
mods/trainer/native/src/spawn_catalog.h (actor archetypes from GameData/Libs/EntityArchetypes/*.xml, which are
CryXmlB binary XML inside GameData*.pak). Both are lists of asset names only.
"""
import glob
import os
import re
import sys
import zipfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cryxml  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GROUPS = [("Pro_Russians", "Pro-Russian militia (hostile)"), ("Russians", "Russians (hostile)"),
          ("Criminals", "Criminals (hostile)"), ("23_society", "23 Society (hostile)"),
          ("Americans", "Americans (neutral)"), ("Pro_Americans", "Pro-Americans"), ("Civilians", "Civilians"),
          ("Aggressive_Animals", "Aggressive animals"), ("Fabular_Characters", "Story characters"),
          ("Characters", "Characters")]


def pak_names(pattern):
    for p in sorted(glob.glob(pattern)):
        z = zipfile.ZipFile(p)
        for i in z.infolist():
            yield z, i


def read_entry(z, i):
    z.fp.seek(i.header_offset + 26)
    n = int.from_bytes(z.fp.read(2), "little")
    z.fp.seek(i.header_offset + 30)
    i.orig_filename = z.fp.read(n).decode("cp437")
    return z.read(i)


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    sdk = os.path.join(sys.argv[1], "GameSDK")

    models = set()
    for _, i in pak_names(os.path.join(sdk, "Objects*.pak")):
        n = i.filename.replace("\\", "/")
        low = n.lower()
        if low.endswith((".cgf", ".cga")) and "_lod" not in low and "/lod" not in low:
            models.add(n)
    out = os.path.join(ROOT, "mods", "trainer", "native", "sgw3_models.txt")
    open(out, "w", encoding="utf-8").write("\n".join(sorted(models, key=str.lower)) + "\n")
    print("models:", len(models))

    # archetype XMLs (later patch paks override earlier ones)
    xmls = {}
    for z, i in pak_names(os.path.join(sdk, "GameData*.pak")):
        n = i.filename.replace("\\", "/")
        if n.lower().startswith("libs/entityarchetypes/") and n.lower().endswith(".xml"):
            xmls[os.path.basename(n).lower()] = read_entry(z, i)
    lines = ["// Generated by tools/gen_catalogs.py from GameData/Libs/EntityArchetypes/*.xml - do not edit.",
             "#pragma once", "struct SpawnEntry { const char *group; const char *archetype; const char *cls; };",
             "static const SpawnEntry kSpawnCatalog[] = {"]
    total = 0
    for fname, label in GROUPS:
        raw = xmls.get(fname.lower() + ".xml")
        if raw is None:
            continue
        x = cryxml.decode(raw) if raw.startswith(b"CryXmlB") else raw.decode("utf-8", "replace")
        lib = re.search(r'<EntityPrototypeLibrary Name="([^"]+)"', x).group(1)
        for name, cls in re.findall(r'<EntityPrototype Name="([^"]+)"[^>]*Class="([^"]+)"', x):
            if cls.startswith("ci_"):
                lines.append('    { "%s", "%s.%s", "%s" },' % (label, lib, name, cls))
                total += 1
    lines.append("};")
    out = os.path.join(ROOT, "mods", "trainer", "native", "src", "spawn_catalog.h")
    open(out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print("spawn entries:", total)


if __name__ == "__main__":
    main()
